version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily
    labels:
      - 'priority:medium'
      - 'type:dependency-upgrade'
    reviewers:
      - quickcase/dev
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - 'priority:low'
      - 'type:dependency-upgrade'
    reviewers:
      - quickcase/ops
