name: Nightly
on:
  schedule:
    - cron: '0 0 * * *'
env:
  GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
  GITHUB_PACKAGE_TOKEN: ${{ secrets.GITHUB_PACKAGE_TOKEN }}
jobs:
  dependency_check:
    name: Dependency checks
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.x
      - name: Analyse dependencies
        run: ./gradlew dependencyCheckAggregate
      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: '#c82829'
          SLACK_TITLE: '[QuickCase Spring Security] Vulnerabilities found'
          SLACK_MESSAGE: Failure during nightly checks
